[google-chrome]
mac., = C-S-tab
mac.. = C-tab
alt.t = C-t
alt.w = C-w
alt.l = C-l

[com-mitchellh-ghostty]
mac.u = C-u
mac.d = C-d
mac.k = C-k
mac.o = C-o

[org-mozilla-firefox]
mac., = C-S-tab
mac.. = C-tab
alt.t = C-t
alt.w = C-w
alt.l = C-l
mac+shift.z = C-A-z
