cask_args appdir: "/Applications"
brew 'git'
brew 'exa'
brew 'bat'
brew 'neovim'
brew 'fish'
brew 'rbenv'
brew 'ruby-build'
brew 'libyaml'
brew 'ccat'

cask 'raycast'
cask 'visual-studio-code'
cask 'docker'
cask 'font-hack-nerd-font'
cask 'kindle'
cask 'cleanmymac'
