cask_args appdir: "/Applications"
brew 'git'
brew 'bat'
brew 'neovim'
brew 'fish'
brew 'rbenv'
brew 'ruby-build'
brew 'libyaml'
brew 'ccat'
brew 'ripgrep'
brew 'fd'
brew 'starship'

cask 'visual-studio-code'
cask 'docker'
cask 'font-hack-nerd-font'
cask 'cleanmymac'
cask 'discord'
cask 'iterm2'
cask 'wezterm'
