#!/bin/sh
# execute permission command $ chmod +x install

set -e

# brew install
if [ ! -e /usr/local/bin/brew ]; then
	  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle -v --file=~/dotfiles/Brewfile

# Create a .config directory
if [ ! -d ~/.config ]; then
	mkdir ~/.config
fi

if [ -e ~/.config/fish/fish_plugins ]; then
  cd ~/
	fisher update
fi

