#!/bin/sh
# execute permission command $ chmod +x install

set -e

# brew install
if [ ! -e /usr/local/bin/brew ]; then
	  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle -v --file=~/dotfiles/Brewfile

# Create a .config directory
if [ ! -d ~/.config ]; then
	mkdir ~/.config
fi

curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

ln -sf ~/dotfiles/.config/fish/config.fish ~/.config/fish/config.fish
ln -sf ~/dotfiles/.config/fish/fish_plugins ~/.config/fish/fish_plugins
ln -sf ~/dotfiles/.hyper.js ~/.hyper.js
ln -sf ~/dotfiles/.gitconfig.alias ~/.gitconfig.alias

if [ -e ~/.config/fish/fish_plugins ]; then
  cd ~/
	fisher update
fi

