vim.pack.add({
    { src = "https://github.com/Saghen/blink.cmp", version = vim.version.range("^1") },
    { src = "https://github.com/ibhagwan/fzf-lua" },
    { src = "https://github.com/lewis6991/gitsigns.nvim" },
    { src = "https://github.com/stevearc/oil.nvim" },
    { src = "https://github.com/refractalize/oil-git-status.nvim" },
    { src = "https://github.com/nvim-mini/mini.icons" },
    { src = "https://github.com/mason-org/mason.nvim" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter-context" },
    { src = "https://github.com/lukas-reineke/indent-blankline.nvim" },
    { src = "https://github.com/nvim-mini/mini.pairs" },
    { src = "https://github.com/nvim-mini/mini.surround" },
    { src = "https://github.com/nvim-mini/mini.cursorword" },
    { src = "https://github.com/folke/which-key.nvim" },
    { src = "https://github.com/b0o/incline.nvim" },
    { src = "https://github.com/folke/tokyonight.nvim" },
    { src = "https://github.com/nickkadutskyi/jb.nvim" },
    { src = "https://github.com/stevearc/aerial.nvim" },
    { src = "https://github.com/stevearc/conform.nvim" },
    { src = "https://github.com/navarasu/onedark.nvim" },
    { src = "https://github.com/morhetz/gruvbox" },
    { src = "https://github.com/delphinus/md-render.nvim" },
    { src = "https://github.com/nvim-tree/nvim-web-devicons" },
    { src = "https://github.com/nvim-tree/nvim-tree.lua" },
    { src = "https://github.com/akinsho/nvim-bufferline.lua" },
    { src = "https://github.com/windwp/nvim-ts-autotag" },
    { src = "https://github.com/karb94/neoscroll.nvim" },
    { src = "https://github.com/nvim-lualine/lualine.nvim" },
})
