[ids]
*

[main]
# Maps capslock to escape when pressed and control when held.
capslock = overload(mac, noop)

[alt]
c = C-insert
v = S-insert
x = S-delete
a = C-a

[mac]
p = up
n = down
b = left
f = right
a = home
e = end
h = backspace
d = delete
k = macro(S-end backspace)
right = M-A-right
left = M-A-left

# Neovim
leftbrace = esc
c = C-c
# Wezterm/Ghostty Leader key
g = A-g
comma = A-comma
dot = A-dot

[mac+shift]
h = A-S-h
j = A-S-j
k = A-S-k
l = A-S-l
