virtual_modifiers:
  - CapsLock

modmap:
  - remap:
      CapsLock:
        held: CapsLock
        alone: [] # 単押し → 何も出力しない
        alone_timeout_millis: 150 # tap/hold判定のしきい値

keymap:
  - name: Terminal系
    application:
      only: com.mitchellh.ghostty
    remap:
      CapsLock-k: C-k
      CapsLock-LeftBrace: Esc
      CapsLock-c: C-c
      CapsLock-u: C-u
      CapsLock-d: C-d
      CapsLock-Space: C-Space
      CapsLock-Shift-h: C-Shift-h
      CapsLock-Shift-j: C-Shift-j
      CapsLock-Shift-k: C-Shift-k
      CapsLock-Shift-l: C-Shift-l
      CapsLock-h: C-h
      CapsLock-j: C-j
      CapsLock-k: C-k
      CapsLock-l: C-l
      CapsLock-o: C-o
      CapsLock-Shift-x: C-Shift-x
      CapsLock-Comma: C-M-b
      CapsLock-Dot: C-M-n
  - name: ブラウザ系
    application:
      only:
        - firefox
        - brave-browser
        - Google-chrome
    remap:
      CapsLock-Comma: C-PageUp
      CapsLock-Dot: C-PageDown

  - name: IDE
    application:
      only:
        - dev.zed.Zed
        - obsidian
        - code
    remap:
      CapsLock-k: C-k
      CapsLock-LeftBrace: Esc
      CapsLock-c: C-c
      CapsLock-u: C-u
      CapsLock-d: C-d

  - name: Zed editor
    application:
      only:
        - dev.zed.Zed
    remap:
      CapsLock-h: Shift-Ctrl-Alt-h
      CapsLock-j: Shift-Ctrl-Alt-j
      CapsLock-l: Shift-Ctrl-Alt-l
      CapsLock-t: Shift-Ctrl-Alt-t
      CapsLock-slash: Shift-Ctrl-Alt-slash

  - remap: # 共通
      CapsLock-p: Up
      CapsLock-n: Down
      CapsLock-b: Left
      CapsLock-f: Right
      CapsLock-a: Home
      CapsLock-e: End
      CapsLock-h: Backspace
      CapsLock-d: Delete
      CapsLock-k: [Shift-End, Backspace]
      CapsLock-Right: Super-Right
      CapsLock-Down: Super-Down
      CapsLock-Left: Super-Left
      CapsLock-Up: Super-Up
      CapsLock-1: Super-1
      CapsLock-2: Super-2
      CapsLock-3: Super-3
      CapsLock-4: Super-4
      CapsLock-5: Super-5
      CapsLock-6: Super-6
      CapsLock-7: Super-7
      CapsLock-8: Super-8
      CapsLock-9: Super-9
      CapsLock-0: Super-0
