require 'config'
require 'keymapping'
require 'plugins'
require 'plugins.telescope'
require 'plugins.nvim-treesitter'
require 'plugins.lsp'
require 'plugins.nvim-autopairs'
require 'plugins.comment'
require 'plugins.nvim-cmp'
require 'plugins.gitsigns'
require 'plugins.toggleterm'
require 'plugins.lualine'
require 'plugins.mason'
require 'plugins.hop'
require 'plugins.onedark'
-- require 'plugins.neosolarized'
