if not vim.g.vscode then
    require 'config'
    require 'keymapping'
    require 'plugins'
    require 'plugins.telescope'
    require 'plugins.lsp'
    require 'plugins.nvim-autopairs'
    require 'plugins.comment'
    require 'plugins.nvim-cmp'
    require 'plugins.gitsigns'
    require 'plugins.toggleterm'
    require 'plugins.lualine'
    require 'plugins.mason'
    require 'plugins.hop'
    -- require 'plugins.onedarkk'
    require 'plugins.nvim-treesitter'
    require 'plugins.lua-snip'
    require 'plugins.mini-indentscope'
    require 'plugins.catppuccin'
end
