onboarding = false
[keys]
prefix = "ctrl+space"
zoom = "prefix+m"       # legacy alias: fullscreen
navigate_workspace_up = "k"
navigate_workspace_down = "j"
next_tab = ["prefix+n", "ctrl+alt+n"]
previous_tab = ["prefix+p", "ctrl+alt+b"]
switch_tab = ["prefix+1..9", "alt+1", "alt+2", "alt+3", "alt+4", "alt+5", "alt+6", "alt+7", "alt+8"]
copy_mode = ["prefix+[", "ctrl+shift+x"]
focus_pane_left = ["prefix+h", "ctrl+shift+h"]
focus_pane_down = ["prefix+j", "ctrl+shift+j"]
focus_pane_up = ["prefix+k", "ctrl+shift+k"]
focus_pane_right = ["prefix+l", "ctrl+shift+l"]

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"
sidebar_start_collapsed = true
sidebar_collapsed_mode = "hidden"

[ui.sound]
enabled = false

[theme]
# name = "gruvbox"
name = "terminal"
auto_switch = false

[[keys.command]]
key = "prefix+shift+l"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[[keys.command]]
key = "alt+9"
type = "shell"
command = "herdr tab focus \"$(herdr tab list | jq -r '.result.tabs as $t | ($t[] | select(.focused) | .workspace_id) as $ws | [$t[] | select(.workspace_id==$ws)] | max_by(.label|tonumber) | .tab_id')\""
description = "Focus last tab in current workspace"
